spring.application.name=A3Dinhhung_SBA301
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=A3Dinhhung_SBA301;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.staff.email=admin@fuhotel.com
app.staff.password=admin123